class Error:
    GAME_ERROR = 'An Error Occurred while playing. Please try later.'
    BOARD_ROW_EXCEEDED = 'Cannot move upwards, reached board end.'
    STATUS_ERROR = 'An Error Occurred while getting Board Status. Please try later.'
    MOVE_ERROR = 'An Error Occurred while moving Player. Please try later.'
    ROLL_ERROR = 'An Error Occurred while rolling Dice. Please try later.'
    BOARD_ERROR = 'An Error Occurred while initializing Board. Please try later.'
    BOARD_VALUE_ERROR = 'An Error Occurred while getting Board Value. Please try later.'
    SNAKE_INIT_ERROR = 'An Error Occurred while initializing Snakes. Please try later.'
    SNAKE_VALUE_ERROR = 'Cannot create Snake. Values are invalid.'
    LADDER_INIT_ERROR = 'An Error Occurred while initializing Ladders. Please try later.'
    LADDER_VALUE_ERROR = 'Cannot create Ladder. Values are invalid.'
    SNAKE_CHECK_ERROR = 'An Error Occurred while checking Snake. Please try later.'
    SNAKE_BITE_ERROR = 'An Error Occurred while biting. Please try later.'
    LADDER_CHECK_ERROR = 'An Error Occurred while checking Ladder. Please try later.'
    LADDER_CLIMB_ERROR = 'An Error Occurred while climbing Ladder. Please try later.'
    SNAKES_AND_LADDERS_ERROR = 'An Error Occurred while checking Snakes and Ladders. Please try later.'